# vim: expandtab:ts=4:sw=4
"""
run_identity_metrics.py

Evaluate standalone body ReID on MOT-format ground-truth boxes.

This script measures the ReID / identity-clustering component independently
from detector and tracker quality according to the project Description.

The pipeline:
    MOT frame + GT bbox -> ReID descriptor -> KNN identity database -> metrics

It uses ground-truth MOT track IDs as clustering labels, but the predicted
identity IDs generated by IdentityDatabase unrelated to the GT IDs.
"""

from __future__ import division, print_function, absolute_import

import argparse
import csv
import json
import sys
import time
from pathlib import Path

import cv2
import numpy as np

sys.path.append(str(Path(__file__).resolve().parent / "src"))

import reids
from identity.database import IdentityDatabase, normalize_feature
from run_tracker import gather_sequence_info, bool_string

from collections import Counter

from sklearn.metrics import (
    calinski_harabasz_score,
    fowlkes_mallows_score,
    silhouette_score,
)


class GroundTruthDetection(object):
    """
    Minimal detection object compatible with the existing ReID plugins.

    ReID plugins normally receive detector outputs that expose a tlwh box,
    confidence, class_id, and possibly a mask, which is all that is needed
    for GT-crop evaluation.
    """

    def __init__(self, tlwh, confidence=1.0, class_id=1):
        self.tlwh = np.asarray(tlwh, dtype=np.float32)
        self.confidence = confidence
        self.class_id = class_id
        self.mask = None

    def to_tlbr(self):
        x, y, w, h = self.tlwh
        return np.asarray([x, y, x + w, y + h], dtype=np.float32)

    def to_xyah(self):
        x, y, w, h = self.tlwh
        return np.asarray([x + w / 2.0, y + h / 2.0, w / h, h], dtype=np.float32)


class SampleLimit(object):
    """Deterministic per-identity sampling cap."""

    def __init__(self, max_per_identity=None):
        self.max_per_identity = max_per_identity
        self.counts = {}

    def accept(self, gt_id):
        if self.max_per_identity is None or self.max_per_identity <= 0:
            return True

        count = self.counts.get(gt_id, 0)
        if count >= self.max_per_identity:
            return False

        self.counts[gt_id] = count + 1
        return True


def clip_tlwh(tlwh, image_width, image_height):
    x, y, w, h = [float(v) for v in tlwh]

    x1 = max(0.0, x)
    y1 = max(0.0, y)
    x2 = min(float(image_width), x + max(0.0, w))
    y2 = min(float(image_height), y + max(0.0, h))

    return np.asarray([x1, y1, x2 - x1, y2 - y1], dtype=np.float32)


def gt_row_unusable(row, *, require_marked, min_visibility):
    """
    Return reason string if a MOT-format GT row should not be used.

    MOTChallenge columns are typically:
        frame, id, x, y, w, h, mark/conf, class, visibility

    The script is defensive because some sequences use -1 placeholders or have
    slightly different conventions.
    """

    if len(row) < 6:
        return "row_short"

    gt_id = int(row[1])
    if gt_id <= 0:
        return "id_negative"

    x, y, w, h = row[2:6]
    if w <= 0 or h <= 0:
        return "wh_not_positive"

    if require_marked and len(row) >= 7 and row[6] <= 0:
        return "marked_ignore"

    if min_visibility is not None and len(row) >= 9:
        if row[8] < min_visibility:
            return "below_min_visibility"

    return None


def safe_silhouette(features, labels, *, metric):
    labels = np.asarray(labels)
    n_samples = len(labels)
    n_labels = len(set(labels.tolist()))

    if n_samples < 3 or n_labels < 2 or n_labels >= n_samples:
        return None

    return float(silhouette_score(features, labels, metric=metric))


def safe_calinski_harabasz(features, labels):
    labels = np.asarray(labels)
    n_samples = len(labels)
    n_labels = len(set(labels.tolist()))

    if n_samples < 3 or n_labels < 2 or n_labels >= n_samples:
        return None

    return float(calinski_harabasz_score(features, labels))


def evaluate(sequence_dir, output_dir, parameters):
    seq_info = gather_sequence_info(sequence_dir)
    sequence_name = seq_info["sequence_name"]

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    reid = reids.create_reid_detector(
        parameters["reid"],
        use_detection_mask=False,
    )

    database = IdentityDatabase(
        max_distance=parameters["identity_max_distance"],
        max_features_per_identity=parameters["max_features_per_identity"],
        knn_k=parameters["knn_k"],
        knn_min_votes=parameters["knn_min_votes"],
    )

    groundtruth = np.asarray(seq_info["groundtruth"])
    if groundtruth.ndim == 1:
        groundtruth = groundtruth.reshape(1, -1)

    features = []
    gt_ids = []
    pred_ids = []
    rows_out = []

    start_time = time.perf_counter()
    skipped = 0
    skip_reasons = Counter()

    for frame_idx in range(seq_info["min_frame_idx"], seq_info["max_frame_idx"] + 1):
        frame_rows = groundtruth[groundtruth[:, 0].astype(int) == frame_idx]
        if len(frame_rows) == 0:
            continue

        image_filename = seq_info["image_filenames"].get(frame_idx)
        if image_filename is None:
            skip_reasons["image_filename_none"] += 1
            skipped += len(frame_rows)
            continue

        frame = cv2.imread(image_filename, cv2.IMREAD_COLOR)
        if frame is None:
            print(f"WARNING: could not read frame: {image_filename}")
            skip_reasons["frame_none"] += 1
            skipped += len(frame_rows)
            continue

        image_height, image_width = frame.shape[:2]

        detections = []
        detection_gt_ids = []

        for row in frame_rows:
            reason = gt_row_unusable(
                row,
                require_marked=parameters["gt_require_marked"],
                min_visibility=parameters["gt_min_visibility"]
            )
            if reason:
                skip_reasons[f"gt_{reason}"] += 1
                skipped += 1
                continue

            tlwh = clip_tlwh(row[2:6], image_width, image_height)
            if tlwh[2] < parameters["min_crop_width"] or tlwh[3] < parameters["min_crop_height"]:
                skip_reasons["tlwh_too_small"] += 1
                skipped += 1
                continue

            detections.append(GroundTruthDetection(tlwh))
            gt_id = int(row[1])
            detection_gt_ids.append(gt_id)

        if not detections:
            continue

        detections = reid.reid(frame, detections)

        for detection, gt_id in zip(detections, detection_gt_ids):
            feature = getattr(detection, "feature", None)
            if feature is None:
                skip_reasons["detection_missing_feature"] += 1
                skipped += 1
                continue

            feature = normalize_feature(feature)
            pred_id, distance = database.match(feature)

            is_new = pred_id is None
            if is_new:
                pred_id = database.create(feature)
            else:
                database.add_sample(pred_id, feature)

            features.append(feature)
            gt_ids.append(gt_id)
            pred_ids.append(pred_id)

            x, y, w, h = detection.tlwh
            rows_out.append({
                "frame": int(frame_idx),
                "gt_id": int(gt_id),
                "pred_id": int(pred_id),
                "distance": "" if distance is None else float(distance),
                "is_new": bool(is_new),
                "x": float(x),
                "y": float(y),
                "w": float(w),
                "h": float(h),
            })

        print(
            f"Processing frame {frame_idx:05d} "
            f"samples={len(features)} identities={len(database.clusters)}\r",
            end="",
        )

    print()

    if not features:
        raise ValueError("No ReID features were collected. Check GT filters and sequence path.")

    features_np = np.vstack(features).astype(np.float32)
    gt_ids_np = np.asarray(gt_ids, dtype=np.int32)
    pred_ids_np = np.asarray(pred_ids, dtype=np.int32)

    elapsed = time.perf_counter() - start_time
    n_samples = int(len(features_np))
    n_gt_ids = int(len(set(gt_ids)))
    n_pred_ids = int(len(set(pred_ids)))

    metrics = {
        "sequence": sequence_name,
        "parameters": parameters,
        "summary": {
            "samples": n_samples,
            "skipped": int(skipped),
            "gt_identities": n_gt_ids,
            "predicted_identities": n_pred_ids,
            "elapsed_seconds": float(elapsed),
            "samples_per_second": float(n_samples / elapsed) if elapsed > 0 else None,
        },
        "metrics": {
            "fowlkes_mallows_pred_vs_gt": float(fowlkes_mallows_score(gt_ids_np, pred_ids_np)),
            "silhouette_pred_cosine": safe_silhouette(features_np, pred_ids_np, metric="cosine"),
            "silhouette_gt_cosine": safe_silhouette(features_np, gt_ids_np, metric="cosine"),
            "calinski_harabasz_pred": safe_calinski_harabasz(features_np, pred_ids_np),
            "calinski_harabasz_gt": safe_calinski_harabasz(features_np, gt_ids_np),
        },
    }

    metrics_path = output_dir / f"{sequence_name}_identity_metrics.json"
    predictions_path = output_dir / f"{sequence_name}_identity_predictions.csv"

    with metrics_path.open("w") as f:
        json.dump(metrics, f, indent=2)

    with predictions_path.open("w", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["frame", "gt_id", "pred_id", "distance", "is_new", "x", "y", "w", "h"],
        )
        writer.writeheader()
        writer.writerows(rows_out)

    print(f"Sequence: {sequence_name}")
    print(f"  samples:              {n_samples}")
    print(f"  skipped:              {skipped}")
    print(f"  GT identities:         {n_gt_ids}")
    print(f"  predicted identities:  {n_pred_ids}")
    print(f"  Fowlkes-Mallows:       {metrics['metrics']['fowlkes_mallows_pred_vs_gt']:.4f}")

    sil_pred = metrics["metrics"]["silhouette_pred_cosine"]
    sil_gt = metrics["metrics"]["silhouette_gt_cosine"]
    ch_pred = metrics["metrics"]["calinski_harabasz_pred"]
    ch_gt = metrics["metrics"]["calinski_harabasz_gt"]

    print(f"  Silhouette pred/cos:   {sil_pred if sil_pred is not None else 'undefined'}")
    print(f"  Silhouette GT/cos:     {sil_gt if sil_gt is not None else 'undefined'}")
    print(f"  Calinski-H pred:       {ch_pred if ch_pred is not None else 'undefined'}")
    print(f"  Calinski-H GT:         {ch_gt if ch_gt is not None else 'undefined'}")
    print(f"  metrics:              {metrics_path}")
    print(f"  predictions:          {predictions_path}")

    if skipped > 0:
        print("\nSkip reasons:")
        for reason, count in skip_reasons.most_common():
            print(f"  {reason}: {count}")

    return metrics


def parse_args():
    parser = argparse.ArgumentParser(
        description="Evaluate standalone body ReID using MOT ground-truth crops."
    )

    parser.add_argument(
        "--sequence_dir",
        required=True,
        help="Path to a MOT-format sequence directory containing img1/ and gt/gt.txt.",
    )
    parser.add_argument(
        "--output_dir",
        required=True,
        help="Directory for metrics JSON and prediction CSV outputs.",
    )
    parser.add_argument(
        "--reid",
        default="mars",
        help="ReID model to evaluate, e.g. mars, osnet_x1_0, osnet_x0_5.",
    )
    parser.add_argument(
        "--identity_max_distance",
        type=float,
        default=0.25,
        help="Maximum cosine distance for matching a descriptor to an existing identity.",
    )
    parser.add_argument(
        "--max_features_per_identity",
        type=int,
        default=100,
        help="Maximum number of descriptors stored per predicted identity.",
    )
    parser.add_argument(
        "--knn_k",
        type=int,
        default=5,
        help="Number of nearest gallery descriptors used for KNN identity voting.",
    )
    parser.add_argument(
        "--knn_min_votes",
        type=int,
        default=1,
        help="Minimum KNN votes required to assign an existing identity.",
    )

    return parser.parse_args()


def main():
    args = parse_args()

    parameters = {
        "reid": args.reid,
        "identity_max_distance": args.identity_max_distance,
        "max_features_per_identity": args.max_features_per_identity,
        "knn_k": args.knn_k,
        "knn_min_votes": args.knn_min_votes,
        "min_crop_width": 4.0,
        "min_crop_height": 8.0,
        "gt_require_marked": False,
        "gt_min_visibility": 0.0,
    }

    evaluate(args.sequence_dir, args.output_dir, parameters)


if __name__ == "__main__":
    main()
